# Define the skeleton of the website/documentation
site_name: openhdemg
site_author: Giacomo Valli & Paul Ritsche
site_description: >-
  All you need to know about openhdemg

# Repository
repo_name: openhdemg
repo_url: https://github.com/GiacomoValliPhD/openhdemg

copyright: Copyright &copy; 2022 - 2024. The openhdemg community

theme:
  name: material
  custom_dir: docs/overrides
  logo: yml_graphics/transp_icon.png
  favicon: yml_graphics/transp_icon.png
  features:
    - content.code.copy
    - announce.dismiss
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css: [docs/custom.css]

# Select a plugin to get the docs from docstrings and setup the numpy stile as
# the default style.
# In order change the docstring_style we need to access:
# mkdocstrings/python/src/mkdocstrings_handlers/python/handler.py
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: 'numpy'
          docstring_section_style: 'spacy'
          show_source: false
          docstring_options:
            ignore_init_summary: True
- search:
    lang: en
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- tags:

# Specify custom pages-menu order.
# If you don’t like a page’s title, you can optionally add another element in
# front of the filename whose title you want to change.
nav:
  - Welcome: index.md
  - About us: about-us.md
  - Quick-Start: quick-start.md
  - Tutorials:
    #- Overview on the tutorials: Tutorials.md
    - For new users:
      - Setup working environment: tutorials/setup_working_env.md
    - Basics of openhdemg:
      - Structure of the emgfile: tutorials/emgfile_structure.md
      - Import from other software: tutorials/import_from_other_software.md
    - Move to newer versions:
      - Convert old .json files: tutorials/convert_old_json_files.md
  - Graphical Interface:
    - Intro: gui_intro.md
    - Basics: gui_basics.md
    - Advanced: gui_advanced.md
    - Settings: gui_settings.md
  - What's New: what's-new.md
  - Contacts: contacts.md
  - Cite us: cite-us.md
  - Contribute: contribute.md
  - ISEK-JEK Tutorials: isek_jek_tutorials.md
  - API Reference:
    - openfiles: api_openfiles.md
    - plotemg: api_plotemg.md
    - analysis: api_analysis.md
    - tools: api_tools.md
    - mathtools: api_mathtools.md
    - muap: api_muap.md
    - electrodes: api_electrodes.md
    - info: api_info.md
    - compatibility: api_compatibility.md
    
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: GiacomoValliPhD
      repo: openhdemg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Modify extra tools.
extra:
  generator: false # Remove 'Made with Material for MkDocs' in the footer.
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GiacomoValliPhD/openhdemg
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/openhdemg
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@openhdemg
#  version:
#    provider: mike # TODO versioning

# Need to have or pip install:
# mkdocs
# mkdocs-autorefs
# mkdocs-material
# mkdocs-material-extensions
# mkdocstrings
# mkdocstrings-python
# mike