[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DL_Track_US"
version = "0.1.2.1"
authors = [
  { name="Paul Ritsche", email="paul.ritsche@unibas.ch" },
  { name="Olivier Seynnes", email="oliviers@nih.no" },
  { name="Neil Cronin", email="neil.j.cronin@jyu.fi" },
]
description = "Automatic analysis of logitudinal muscle ultrasonography images"
readme = "README_Pypi.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
dependencies = [
    "jupyter==1.0.0",
    "Keras==2.10.0",
    "matplotlib==3.6.1",
    "numpy==1.23.4",
    "opencv-contrib-python==4.6.0.66",
    "openpyxl==3.0.10",
    "pandas==1.5.1",
    "Pillow==9.2.0",
    "pre-commit==2.17.0",
    "scikit-image==0.19.3",
    "scikit-learn==1.1.2",
    "sewar==0.4.5",
    "tensorflow==2.10.0",
    "tqdm==4.64.1"
  ]

[project.urls]
"Homepage" = "https://github.com/PaulRitsche/DL_Track_US"
"Bug Tracker" = "https://github.com/PaulRitsche/DL_Track_US/issues"
