name: ci 
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      # Old unpinned dependencies
      # - run: pip install mkdocs-material
      # - run: pip install mkdocs-material-extensions
      # - run: pip install mkdocs-autorefs
      # - run: pip install mkdocstrings
      # - run: pip install mkdocstrings-python
      # - run: pip install livereload

      - run: pip install griffe==1.5.7
      - run: pip install mkdocs==1.6.1
      - run: pip install mkdocs-autorefs==1.3.1
      - run: pip install mkdocs-get-deps==0.2.0
      - run: pip install mkdocs-material==9.6.4
      - run: pip install mkdocs-material-extensions==1.3.1
      - run: pip install mkdocstrings==0.28.1
      - run: pip install mkdocstrings-python==1.15.0
      - run: pip install livereload

      - run: mkdocs gh-deploy --force
